### PR TITLE
remove json.dumps from request response

### PR DESCRIPTION
**Pull request by Sajo8**
I can make another PR for convertig stuff to snake case for the sweet sweet pythonic feel

### CODE REVIEW

**Review by fexra — CHANGES_REQUESTED** [review]
If we were using something like doxygen it would make sense to put the documentation in the code, but from the development point of view it clutters the code. Makes it hard to find / have an oversight and turns a small file into a large one. Also devs will most likely go to the readme or docs instead of some obscure file in a package which they installed with a package manager.

I suggest removing the the docs, keep the json.dumps removal change.

**Comment by Sajo8** [comment]
:t_wojak: i worked so hard on it, too

**Comment by Sajo8** [comment]
can we get these sort of docs then?
with the args and stuff

**Comment by Sajo8** [comment]
and the response (important)

**Comment by Sajo8** [comment]
done

**Review by fexra — APPROVED** [review]

**Comment by fexra** [comment]
> can we get these sort of docs then?
> with the args and stuff

https://trtl.services/documentation

**Pull request merged**
